version: '3.1'

services:
  db:
    image: 'mysql:8.0.30'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: hibernate_app
      MYSQL_ROOT_PASSWORD: hibernate_app
    ports:
      - '3306:3306'
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
